- name: Install node locally
  hosts: localhost
  become: true
  tasks:
    - name: Include Namada role
      include_role:
        name: cosmos_namada_configure
      when: netname == 'namada_mainnet'

    - name: Include other roles
      include_role:
        name: "{{ item }}"
      loop:
        - cosmos_software
        - cosmos_install
        - cosmos_init
        - cosmos_configure
        - cosmos_start
      when: netname != 'namada_mainnet' 
