config_port_changes:
  'laddr = "tcp://0.0.0.0:26656"': 'laddr = "tcp://0.0.0.0:{{ custom_port_prefix }}56"'
  'laddr = "tcp://127.0.0.1:26657"': 'laddr = "tcp://0.0.0.0:{{ custom_port_prefix }}57"'
  'proxy_app = "tcp://127.0.0.1:26658"': 'proxy_app = "tcp://127.0.0.1:{{ custom_port_prefix }}58"'
  'prometheus_listen_addr = ":26660"': 'prometheus_listen_addr = ":{{ custom_port_prefix }}61"'
  'pprof_laddr = "localhost:6060"': 'pprof_laddr = "localhost:{{ custom_port_prefix }}60"'

# app_port_changes:
#   ':1317': 'address = "tcp://0.0.0.0:{{ custom_port_prefix }}17"'
#   ':8080': 'address = ":{{ custom_port_prefix }}80"'
#   ':9090': 'address = "0.0.0.0:{{ custom_port_prefix }}90"'
#   ':9091': 'address = "0.0.0.0:{{ custom_port_prefix }}91"'

app_port_changes:
  'address = "tcp://localhost:1317"': 'address = "tcp://0.0.0.0:{{ custom_port_prefix }}17"'
  ':8080': 'address = ":{{ custom_port_prefix }}80"'
  'address = "0.0.0.0:9090"': 'address = "0.0.0.0:{{ custom_port_prefix }}90"'
  'address = "0.0.0.0:9091"': 'address = "0.0.0.0:{{ custom_port_prefix }}91"'

pruning_default: 
  'pruning = "': 'pruning = "custom"'
  'pruning-keep-recent = "': 'pruning-keep-recent = "100"'
  'pruning-interval = "': 'pruning-interval = "19"'
  
pruning_relay:
  'pruning = "': 'pruning = "custom"'
  'pruning-keep-recent = "': 'pruning-keep-recent = "100"'
  'pruning-interval = "': 'pruning-interval = "19"'
  'snapshot-interval = ': 'snapshot-interval = 1000'
  'snapshot-keep-recent = ': 'snapshot-keep-recent = 2'
